/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssd.task.pkg3;

/**
 *
 * @author thoma
 */
public class AMSGUI_FieldsPanel2_Options extends javax.swing.JPanel {

    /**
     * Creates new form AMSGUI_FieldsOptionsPanel
     */
    public AMSGUI_FieldsPanel2_Options() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel2 = new javax.swing.JLabel();
        jbtn_checkCrops = new javax.swing.JButton();
        jbtn_recordHarvest = new javax.swing.JButton();
        jbtn_recordPlanting = new javax.swing.JButton();
        jbtn_back = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 0));
        setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("View Fields - Field");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 21, 0, 0);
        add(jLabel2, gridBagConstraints);

        jbtn_checkCrops.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtn_checkCrops.setText("Check Crops");
        jbtn_checkCrops.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 195;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 9, 0, 33);
        add(jbtn_checkCrops, gridBagConstraints);

        jbtn_recordHarvest.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtn_recordHarvest.setText("Record Harvest");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 161;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 9, 0, 33);
        add(jbtn_recordHarvest, gridBagConstraints);

        jbtn_recordPlanting.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtn_recordPlanting.setText("Record Planting");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 161;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 9, 21, 33);
        add(jbtn_recordPlanting, gridBagConstraints);

        jbtn_back.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtn_back.setText("Back");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 0);
        add(jbtn_back, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    public javax.swing.JButton jbtn_back;
    public javax.swing.JButton jbtn_checkCrops;
    public javax.swing.JButton jbtn_recordHarvest;
    public javax.swing.JButton jbtn_recordPlanting;
    // End of variables declaration//GEN-END:variables
}
