/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssd.task.pkg3;

/**
 *
 * @author thoma
 */
public class FieldsPanel2_Options extends javax.swing.JPanel {

    /**
     * Creates new form AMSGUI_FieldsOptionsPanel
     */
    public FieldsPanel2_Options() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_checkCrops = new javax.swing.JButton();
        jbtn_recordHarvest = new javax.swing.JButton();
        jbtn_recordPlanting = new javax.swing.JButton();
        jbtn_back = new javax.swing.JButton();
        jbl_fieldname = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn_checkCrops.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtn_checkCrops.setText("Check Crops");
        jbtn_checkCrops.setName(""); // NOI18N
        add(jbtn_checkCrops, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 358, 57));

        jbtn_recordHarvest.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtn_recordHarvest.setText("Record Harvest");
        add(jbtn_recordHarvest, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 358, 57));

        jbtn_recordPlanting.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtn_recordPlanting.setText("Record Planting");
        add(jbtn_recordPlanting, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 358, 57));

        jbtn_back.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtn_back.setText("Back");
        add(jbtn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jbl_fieldname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbl_fieldname.setText("View Fields - Field");
        add(jbl_fieldname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jbl_fieldname;
    public javax.swing.JButton jbtn_back;
    public javax.swing.JButton jbtn_checkCrops;
    public javax.swing.JButton jbtn_recordHarvest;
    public javax.swing.JButton jbtn_recordPlanting;
    // End of variables declaration//GEN-END:variables
}
