/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssd.task.pkg3;

/**
 *
 * @author thoma
 */
public class FieldsPanel2_Options extends javax.swing.JPanel {

    /**
     * Creates new form AMSGUI_FieldsOptionsPanel
     */
    public FieldsPanel2_Options() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbl_username = new javax.swing.JLabel();
        jbtn_checkCrops = new javax.swing.JButton();
        jbtn_recordHarvest = new javax.swing.JButton();
        jbtn_recordPlanting = new javax.swing.JButton();
        jbtn_back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbl_username.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbl_username.setText("Welcome,");
        add(jbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jbtn_checkCrops.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtn_checkCrops.setText("Check Crops");
        jbtn_checkCrops.setName(""); // NOI18N
        add(jbtn_checkCrops, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 358, 57));

        jbtn_recordHarvest.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtn_recordHarvest.setText("Record Harvest");
        add(jbtn_recordHarvest, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 358, 57));

        jbtn_recordPlanting.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtn_recordPlanting.setText("Record Planting");
        add(jbtn_recordPlanting, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 358, 57));

        jbtn_back.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtn_back.setText("Back");
        add(jbtn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 17, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("View Fields - Field");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Welcome,");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jbl_username;
    public javax.swing.JButton jbtn_back;
    public javax.swing.JButton jbtn_checkCrops;
    public javax.swing.JButton jbtn_recordHarvest;
    public javax.swing.JButton jbtn_recordPlanting;
    // End of variables declaration//GEN-END:variables
}
