/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssd.task.pkg3;

/**
 *
 * @author thoma
 */
public class FieldsPanel3_CheckCrops extends javax.swing.JPanel {

    /**
     * Creates new form AMSGUI_FieldsPanel3_CheckCrops
     */
    public FieldsPanel3_CheckCrops() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_soilAcidity = new javax.swing.JTextField();
        jtf_airTemp = new javax.swing.JTextField();
        jtf_soilMoisture = new javax.swing.JTextField();
        jtf_light = new javax.swing.JTextField();
        jtf_soilTemp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbl_title = new javax.swing.JLabel();
        jbtn_back = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jtf_soilAcidity, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 150, -1));
        add(jtf_airTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 150, -1));
        add(jtf_soilMoisture, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 150, -1));
        add(jtf_light, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 150, -1));
        add(jtf_soilTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Soil Acidity:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Soil Temperature:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Soil Moisture:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Light:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Air Temperature:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jbl_title.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jbl_title.setText("View Fields - Check Crops");
        add(jbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jbtn_back.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtn_back.setText("Back");
        add(jbtn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jbl_title;
    public javax.swing.JButton jbtn_back;
    public javax.swing.JTextField jtf_airTemp;
    public javax.swing.JTextField jtf_light;
    public javax.swing.JTextField jtf_soilAcidity;
    public javax.swing.JTextField jtf_soilMoisture;
    public javax.swing.JTextField jtf_soilTemp;
    // End of variables declaration//GEN-END:variables
}
