/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssd.task.pkg3;

import java.util.Random;

/**
 *
 * @author thoma
 */
public class FieldsPanel3_CheckCrops extends javax.swing.JPanel {
    
    private static Random numberGen = new Random();
    Farmer currentFarmer;
    Field currentField;

    /**
     * Creates new form AMSGUI_FieldsPanel3_CheckCrops
     */
    public FieldsPanel3_CheckCrops() {
        initComponents();
    }
    
    private String ranNum()
    {
        return (Math.round((numberGen.nextDouble()*2000))/100) + "";
    }
    
    //----------------
    //populate the text boxes with the values from current field's sensors
    //hopefully dynamically generate labels and text boxes if we're allowing the sddition of sensors
    //if so need add and remove sensor buttons
    //update button? or try to auto update at intervals?
    //----------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtValue2 = new javax.swing.JTextField();
        txtValue4 = new javax.swing.JTextField();
        txtValue1 = new javax.swing.JTextField();
        txtValue5 = new javax.swing.JTextField();
        txtValue3 = new javax.swing.JTextField();
        lblType2 = new javax.swing.JLabel();
        lblType3 = new javax.swing.JLabel();
        lblType1 = new javax.swing.JLabel();
        lblType5 = new javax.swing.JLabel();
        lblType4 = new javax.swing.JLabel();
        jbl_title = new javax.swing.JLabel();
        jbtn_back = new javax.swing.JButton();
        btnGetReadings = new javax.swing.JButton();
        cmbSensorSelect = new javax.swing.JComboBox<>();
        btnAddSensor = new javax.swing.JButton();
        btnRemoveSensor1 = new javax.swing.JButton();
        btnRemoveSensor2 = new javax.swing.JButton();
        btnRemoveSensor3 = new javax.swing.JButton();
        btnRemoveSensor4 = new javax.swing.JButton();
        btnRemoveSensor5 = new javax.swing.JButton();
        btnPreviousPage = new javax.swing.JButton();
        btnNextPage = new javax.swing.JButton();
        lblPageNumber = new javax.swing.JLabel();
        lblUnit1 = new javax.swing.JLabel();
        lblUnit2 = new javax.swing.JLabel();
        lblUnit3 = new javax.swing.JLabel();
        lblUnit4 = new javax.swing.JLabel();
        lblUnit5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtValue2.setName("txtSoilAcidity"); // NOI18N
        add(txtValue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 80, -1));

        txtValue4.setName("txtAirTemperature"); // NOI18N
        add(txtValue4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 80, -1));

        txtValue1.setName("txtSoilMoisture"); // NOI18N
        add(txtValue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 80, -1));

        txtValue5.setName("txtLight"); // NOI18N
        add(txtValue5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 80, -1));

        txtValue3.setName("txtSoilTemperature"); // NOI18N
        add(txtValue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 80, -1));

        lblType2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblType2.setText("No sensor detected");
        add(lblType2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        lblType3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblType3.setText("No sensor detected");
        add(lblType3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        lblType1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblType1.setText("No sensor detected");
        add(lblType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lblType5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblType5.setText("No sensor detected");
        add(lblType5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        lblType4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblType4.setText("No sensor detected");
        add(lblType4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jbl_title.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jbl_title.setText("View Fields - Check Crops");
        add(jbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jbtn_back.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtn_back.setText("Back");
        add(jbtn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnGetReadings.setText("Get readings");
        btnGetReadings.setName("btnGetReadings"); // NOI18N
        btnGetReadings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetReadingsActionPerformed(evt);
            }
        });
        add(btnGetReadings, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        cmbSensorSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Air humidity", "Air temperature", "Light level", "Soil acidity", "Soil moisture", "Soil temperature" }));
        add(cmbSensorSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 130, 30));

        btnAddSensor.setText("Add Sensor");
        add(btnAddSensor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 100, -1));

        btnRemoveSensor1.setText("Remove sensor");
        add(btnRemoveSensor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        btnRemoveSensor2.setText("Remove sensor");
        add(btnRemoveSensor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        btnRemoveSensor3.setText("Remove sensor");
        add(btnRemoveSensor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        btnRemoveSensor4.setText("Remove sensor");
        add(btnRemoveSensor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        btnRemoveSensor5.setText("Remove sensor");
        add(btnRemoveSensor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        btnPreviousPage.setText("Previous page");
        btnPreviousPage.setEnabled(false);
        add(btnPreviousPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, -1));

        btnNextPage.setText("Next page");
        btnNextPage.setEnabled(false);
        add(btnNextPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 100, -1));
        add(lblPageNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 20, 20));
        add(lblUnit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 40, 20));
        add(lblUnit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 40, 20));
        add(lblUnit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 40, 20));
        add(lblUnit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 40, 20));
        add(lblUnit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 40, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetReadingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetReadingsActionPerformed
        
    }//GEN-LAST:event_btnGetReadingsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddSensor;
    public javax.swing.JButton btnGetReadings;
    public javax.swing.JButton btnNextPage;
    public javax.swing.JButton btnPreviousPage;
    public javax.swing.JButton btnRemoveSensor1;
    public javax.swing.JButton btnRemoveSensor2;
    public javax.swing.JButton btnRemoveSensor3;
    public javax.swing.JButton btnRemoveSensor4;
    public javax.swing.JButton btnRemoveSensor5;
    public javax.swing.JComboBox<String> cmbSensorSelect;
    public javax.swing.JLabel jbl_title;
    public javax.swing.JButton jbtn_back;
    public javax.swing.JLabel lblPageNumber;
    public javax.swing.JLabel lblType1;
    public javax.swing.JLabel lblType2;
    public javax.swing.JLabel lblType3;
    public javax.swing.JLabel lblType4;
    public javax.swing.JLabel lblType5;
    public javax.swing.JLabel lblUnit1;
    public javax.swing.JLabel lblUnit2;
    public javax.swing.JLabel lblUnit3;
    public javax.swing.JLabel lblUnit4;
    public javax.swing.JLabel lblUnit5;
    public javax.swing.JTextField txtValue1;
    public javax.swing.JTextField txtValue2;
    public javax.swing.JTextField txtValue3;
    public javax.swing.JTextField txtValue4;
    public javax.swing.JTextField txtValue5;
    // End of variables declaration//GEN-END:variables
}
