/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssd.task.pkg3;

/**
 *
 * @author b3014277
 */
public class logInPanel extends javax.swing.JPanel {

    /**
     * Creates new form logInPanel
     */
    public logInPanel() {
        initComponents();
    }
    private SetOfUsers users;
    private SetOfFarmers farmers; 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtf_password = new javax.swing.JPasswordField();
        jbtn_submit = new javax.swing.JButton();
        jtf_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtn_create = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 0));

        jtf_password.setText("password");
        jtf_password.setName("jPasswordField_password"); // NOI18N

        jbtn_submit.setText("Submit");
        jbtn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_submitActionPerformed(evt);
            }
        });

        jtf_username.setText("admin");
        jtf_username.setName("jtf_username"); // NOI18N
        jtf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_usernameActionPerformed(evt);
            }
        });

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        jbtn_create.setText("Create Account");
        jbtn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_createActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_create)
                    .addComponent(jbtn_submit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtf_username)
                        .addComponent(jtf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtn_submit)
                .addGap(18, 18, 18)
                .addComponent(jbtn_create)
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_submitActionPerformed

//        User currentUser = users.login(
//            jtf_username.getText(),
//            new String( jtf_password.getPassword() )
//        );
//
//        if( currentUser != null){
//            this.jtf_username.setText("");
//            this.jtf_password.setText("");
//
//            new AMSGUI_User(currentUser, this).setVisible(true);
//        }
//        else
//        {
//            Farmer currentFarmer = farmers.login(
//                jtf_username.getText(),
//                new String( jtf_password.getPassword())
//            );
//
//            if( currentFarmer != null)
//            {
//                this.jtf_username.setText("");
//                this.jtf_password.setText("");
//
//                new AMSGUI_Farmer(currentFarmer, this).setVisible(true);
//            }
//            else
//            JOptionPane.showMessageDialog(this, "Invalid username or password!");
//        }
    }//GEN-LAST:event_jbtn_submitActionPerformed

    private void jtf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_usernameActionPerformed

    private void jbtn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_createActionPerformed
        // TODO add your handling code here:

        //this.setVisible(false);

        //new AccountCreationPanel().setVisible(true);

    }//GEN-LAST:event_jbtn_createActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JButton jbtn_create;
    public javax.swing.JButton jbtn_submit;
    public javax.swing.JPasswordField jtf_password;
    public javax.swing.JTextField jtf_username;
    // End of variables declaration//GEN-END:variables
}
