/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssd.task.pkg3;

import javax.swing.DefaultListModel;

/**
 *
 * @author thoma
 */
public class ManageFarmersPanel extends javax.swing.JPanel {
    
    public DefaultListModel model;
    
    /**
     * Creates new form ManageFarmersPanel
     */
    public ManageFarmersPanel() {
        initComponents();
        model = new DefaultListModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtn_back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlPickFarmer = new javax.swing.JList<>();
        jbtn_unblockFarmer = new javax.swing.JButton();
        jbtn_blockFarmer = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Farmers - Add to Block List");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 31, 358, 18));

        jbtn_back.setText("Back");
        add(jbtn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 235, 89, -1));

        jlPickFarmer.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlPickFarmer);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 70, 427, 147));

        jbtn_unblockFarmer.setLabel("Unblock Farmer");
        add(jbtn_unblockFarmer, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        jbtn_blockFarmer.setLabel("Block Farmer");
        add(jbtn_blockFarmer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtn_back;
    public javax.swing.JButton jbtn_blockFarmer;
    public javax.swing.JButton jbtn_unblockFarmer;
    public javax.swing.JList<String> jlPickFarmer;
    // End of variables declaration//GEN-END:variables
}
