/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssd.task.pkg3;

/**
 *
 * @author thoma
 */
public class OrdersPanel6_OrderDetails extends javax.swing.JPanel {

    /**
     * Creates new form OrdersPanel6_OrderDetails
     */
    public OrdersPanel6_OrderDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_location = new javax.swing.JLabel();
        lbl_product = new javax.swing.JLabel();
        lbl_delivery = new javax.swing.JLabel();
        lbl_phone = new javax.swing.JLabel();
        lbl_price = new javax.swing.JLabel();
        jbtn_sendOrder = new javax.swing.JButton();
        jbtn_back = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 153, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Make an Order - Farmer Selection");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 11, 358, 18));

        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 32, -1, -1));

        jLabel3.setText("Location:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 60, -1, -1));

        jLabel4.setText("Product:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 119, -1, -1));

        jLabel5.setText("Delivery Date:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 146, -1, -1));

        jLabel6.setText("Phone:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 90, -1, -1));

        jLabel7.setText("Price:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 174, -1, -1));

        lbl_name.setText("jLabel2");
        add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 32, -1, -1));

        lbl_location.setText("jLabel2");
        add(lbl_location, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 60, -1, -1));

        lbl_product.setText("jLabel2");
        add(lbl_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 119, -1, -1));

        lbl_delivery.setText("jLabel2");
        add(lbl_delivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 146, -1, -1));

        lbl_phone.setText("jLabel2");
        add(lbl_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 90, -1, -1));

        lbl_price.setText("jLabel2");
        add(lbl_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 174, -1, -1));

        jbtn_sendOrder.setText("Order");
        add(jbtn_sendOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 203, 314, -1));

        jbtn_back.setText("Back");
        add(jbtn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 89, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JButton jbtn_back;
    public javax.swing.JButton jbtn_sendOrder;
    public javax.swing.JLabel lbl_delivery;
    public javax.swing.JLabel lbl_location;
    public javax.swing.JLabel lbl_name;
    public javax.swing.JLabel lbl_phone;
    public javax.swing.JLabel lbl_price;
    public javax.swing.JLabel lbl_product;
    // End of variables declaration//GEN-END:variables
}
