/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssd.task.pkg3;

/**
 *
 * @author thoma
 */
public class OrdersPanel4_ProductSelection extends javax.swing.JPanel {

    /**
     * Creates new form OrderPanel4_ProductSelection
     */
    public OrdersPanel4_ProductSelection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jrb_sweetcorn = new javax.swing.JRadioButton();
        jrb_peas = new javax.swing.JRadioButton();
        jrb_sprouts = new javax.swing.JRadioButton();
        jrb_potatoes = new javax.swing.JRadioButton();
        jrb_broccoli = new javax.swing.JRadioButton();
        jrb_carrots = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jbtn_selectCrop = new javax.swing.JButton();
        jbtn_back = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 0));

        buttonGroup1.add(jrb_sweetcorn);
        jrb_sweetcorn.setText("Sweetcorn");

        buttonGroup1.add(jrb_peas);
        jrb_peas.setText("Peas");

        buttonGroup1.add(jrb_sprouts);
        jrb_sprouts.setText("Sprouts");

        buttonGroup1.add(jrb_potatoes);
        jrb_potatoes.setText("Potatoes");

        buttonGroup1.add(jrb_broccoli);
        jrb_broccoli.setText("Broccoli");

        buttonGroup1.add(jrb_carrots);
        jrb_carrots.setText("Carrots");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Make an Order - Product Selection");

        jbtn_selectCrop.setText("Make an Order");

        jbtn_back.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb_carrots)
                            .addComponent(jrb_peas)
                            .addComponent(jrb_sweetcorn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb_broccoli)
                            .addComponent(jrb_sprouts)
                            .addComponent(jrb_potatoes)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jbtn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jbtn_selectCrop, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrb_carrots)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_sweetcorn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_peas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrb_sprouts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_potatoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_broccoli)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_selectCrop)
                    .addComponent(jbtn_back))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JButton jbtn_back;
    public javax.swing.JButton jbtn_selectCrop;
    public javax.swing.JRadioButton jrb_broccoli;
    public javax.swing.JRadioButton jrb_carrots;
    public javax.swing.JRadioButton jrb_peas;
    public javax.swing.JRadioButton jrb_potatoes;
    public javax.swing.JRadioButton jrb_sprouts;
    public javax.swing.JRadioButton jrb_sweetcorn;
    // End of variables declaration//GEN-END:variables
}
