/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cssd.task.pkg3;

/**
 *
 * @author thoma
 */
public class OrdersPanel1_User_Selection extends javax.swing.JPanel {

    /**
     * Creates new form AMSGUI_OrdersPanel
     */
    public OrdersPanel1_User_Selection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtn_makeOrder = new javax.swing.JButton();
        jbtn_orderHistory = new javax.swing.JButton();
        jbtn_manageFarmers = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn_back.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtn_back.setText("Back");
        add(jbtn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("View Orders");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jbtn_makeOrder.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtn_makeOrder.setText("Make an Order");
        jbtn_makeOrder.setName(""); // NOI18N
        add(jbtn_makeOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 358, 57));

        jbtn_orderHistory.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtn_orderHistory.setText("Order History");
        add(jbtn_orderHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 358, 57));

        jbtn_manageFarmers.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtn_manageFarmers.setText("Manage farmers");
        add(jbtn_manageFarmers, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 358, 57));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    public javax.swing.JButton jbtn_back;
    public javax.swing.JButton jbtn_makeOrder;
    public javax.swing.JButton jbtn_manageFarmers;
    public javax.swing.JButton jbtn_orderHistory;
    // End of variables declaration//GEN-END:variables
}
